<div style="width:760px">
<a href="./">Home</a><br>
<font color="green" size="10">Conference Fees</font><br />
<div style="font-family:verdana;padding:20px;width:700px;height:400px;border-radius:20px;border:10px solid #EE872A;">
<table width="700" border="0" cellpadding="6">
  <tr>
    <th width="300" scope="row"><div align="left"><b>Conference</b></div></th>
    <td width="370"><b>€150</b></td>
  </tr>
</table>
<div style="margin-left:20px;">
<ul>
	<li>	Includes participation in all the conference sessions, conference material, lunch on Thursday and Friday and all coffee/tea during the breaks. </li>
</ul>
<br />
</div>
<table width="700" border="0" cellpadding="6">
  <tr>
    <th width="300" scope="row"><div align="left"><b>Evening programme</b></div></th>
    <td width="370"><b>€50,00 (incl. 19% VAT)</b></td>
  </tr>
</table>
	<div style="margin-left:20px;">

		<ul>
			<li>	Includes dinner, evening concert and Big Band on Thursday.</li>
		</ul>
	</div>


</div>