<div class="hero-unit" style="width:1350px">
<div style="width:1200px">
<a href="./">Home</a><br /><br />
<h3>Hotel Information</h3><br />
<p style="width:900px">
Please note that you are responsible for the hotel booking. The following list aims only to assist you in choosing a hotel in Chemnitz.
The hotels listed below are ordered ascending according to the distance to the conference. More Information about hotels in Chemnitz you find on Internet at <a href="http://www.booking.com">http://www.booking.com</a>
</p><br/>
<table width="1399" height="351" border="0" cellpadding="6">
  <tr>
    <th width="217" scope="row"><div align="left"><strong>Hotel</strong></div></th>
    <td width="183"><div align="left"><strong>Address</strong></div></td>
    <td width="185"><div align="left"><strong>Telephone</strong></div></td>
    <td width="196"><div align="left"><strong>Telefax</strong></div></td>
    <td width="93"><div align="left"><strong>Single</strong></div></td>
    <td width="84"><div align="left"><strong>Double</strong></div></td>
    <td width="82"><div align="left"><strong>E-Mail</strong></div></td>
    <td width="88"><div align="left"><strong>Internet</strong></div></td>
    <td width="62"><div align="left"><strong>Map</strong></div></td>
    <td width="67"><div align="left"><strong>Route</strong></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="left">SeaSide<br />
Residenz Hotel****</div></th>
    <td><div align="left">Bernsdorfer&nbsp;Straße&nbsp;2<br />
09126&nbsp;Chemnitz</div></td>
    <td><div align="left">+49&nbsp;(0)&nbsp;371&nbsp;3551-0</div></td>
    <td><div align="left">+49&nbsp;(0)&nbsp;371&nbsp;3551-122</div></td>
    <td><div align="left">64,00&nbsp;€</div></td>
    <td><div align="left">81,00&nbsp;€</div></td>
    <td><div align="left"><a href="mailto:info@residenzhotelchemnitz.de"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/email.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/email.gif" /></a></div></td>
    <td><div align="left"><a href="http://www.residenz-hotel-chemnitz.de/" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/internet.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/internet.gif" /></a></div></td>
    <td><div align="left"><a href="http://maps.google.de/?q=09126+Chemnitz+Bernsdorfer+Stra%DFe+2&amp;t=h" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/maps.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/maps.gif" /></a></div></td>
    <td><div align="left"><a href="http://maps.google.de/?daddr=09126+Chemnitz+Bernsdorfer+Stra%DFe+2&amp;t=s" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/route.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/route.gif" /></a></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="left">Mercure Hotel<br />
Kongress Chemnitz***</div></th>
    <td><div align="left">Brückenstraße&nbsp;19<br />
09111&nbsp;Chemnitz</div></td>
    <td><div align="left">+49&nbsp;(0)&nbsp;371&nbsp;683-0</div></td>
    <td><div align="left">+49&nbsp;(0)&nbsp;371&nbsp;683505</div></td>
    <td><div align="left">51,00&nbsp;€</div></td>
    <td><div align="left">74,00&nbsp;€</div></td>
    <td><div align="left"><a href="mailto:h1581@accor.com"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/email.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/email.gif" /></a></div></td>
    <td><div align="left"><a href="http://www.mercure.com/de/hotel-1581-mercure-hotel-kongress-chemnitz/" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/internet.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/internet.gif" /></a></div></td>
    <td><div align="left"><a href="http://maps.google.de/?q=09111+Chemnitz+Br%FCckenstra%DFe+19&amp;t=h" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/maps.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/maps.gif" /></a></div></td>
    <td><div align="left"><a href="http://maps.google.de/?daddr=09111+Chemnitz+Br%FCckenstra%DFe+19&amp;t=s" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/route.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/route.gif" /></a></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="left">Hotel an der Oper****</div></th>
    <td>Straße&nbsp;der&nbsp;Nationen&nbsp;56<br />
09111&nbsp;Chemnitz</td>
    <td><div align="left">+49&nbsp;(0)&nbsp;371&nbsp;681-0</div></td>
    <td><div align="left">+49&nbsp;(0)&nbsp;371&nbsp;670606</div></td>
    <td><div align="left">79,00&nbsp;€</div></td>
    <td><div align="left">109,00&nbsp;€</div></td>
    <td><a href="mailto:info@hoteloper-chemnitz.de"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/email.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/email.gif" /></a></td>
    <td><div align="left"><a href="http://www.hoteloper-chemnitz.de/" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/internet.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/internet.gif" /></a></div></td>
    <td><div align="left"><a href="http://maps.google.de/?q=09111+Chemnitz+Stra%DFe+der+Nationen+56&amp;t=h" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/maps.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/maps.gif" /></a></div></td>
    <td><div align="left"><a href="http://maps.google.de/?daddr=09111+Chemnitz+Stra%DFe+der+Nationen+56&amp;t=s" target="_blank"><img border="0" width="38" height="38" src="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/route.gif" alt="http://www.tu-chemnitz.de/mb/FoerdTech/ctt/icons/route.gif" /></a></div></td>
  </tr>
  <tr>
    <th scope="row"><div align="left">Günnewig Hotel<br />
Chemnitzer Hof****</div></th>
    <td><div align="left">Theaterplatz&nbsp;4<br />
09111&nbsp;Chemnitz</div></td>
    <td><div align="left"></div></td>
    <td><div align="left"></div></td>
    <td><div align="left">99,00€</div></td>
    <td><div align="left">119,00€</div></td>
    <td><div align="left"></div></td>
    <td><div align="left"></div></td>
    <td><div align="left"></div></td>
    <td><div align="left"></div></td>
  </tr>
</table>
</div>
</div>