<div class="hero-unit">
<div style="font-family:verdana;padding:20px;width:900px;height:400px;border-radius:20px;border:0px solid #EE872A;">
<a href="./conferencefees">Conference Fees</a> | <a href="./Hotel">Hotel information</a><br /><br />
<b>(<a href="./add">Click here</a> to register for the International Conference)<br/>
<p>(please be aware that the conference allows a limited numbers of participants)  </b></p>

</div>
