<div class="hero-unit">
<div style="font-family:verdana;padding:20px;width:900px;height:400px;border-radius:20px;border:0px solid #EE872A;">

<a href="./conferencefees">Conference Fees</a> | <a href="./Hotel">Hotel information</a><br /><br />

<div>
    <h2>International Merge Technologies Conference – Lightweight Structures</h2>
    <h3>24-25 October 2013</h3>
    <h4>Location: Virtual Reality Center, Fraunhofer IWU, Chemnitz, Germany</h4>
    The conference is aimed to present the latest developments for the resource-efficient mass-production of lightweight structures including:

    <ul>

        <li>In-line processing of semi-finished products and performs for hybrid lightweight structures</li>

        <li>Combination of metal and textile/plastics processing systems</li>

        <li>In-situ-processes for the efficient integration of textiles, metallic and electronic components in
            plastics
        </li>

        <li>Integration technologies of micro-and nanosystems for sensing, actuating and electronic functionalisation
        </li>

        <li>Interface technologies for formation of reliable bonds of hybrid structures</li>

        <li>Integrative simulation and simultaneous optimization of manufacturing and design</li>

    </ul>

    <strong><a href="./add">Registration</a> will be available starting June, 2013.<br />
	(please be aware that the conference allows a limited numbers of participants)
	</strong>

    <h4>Further Information</h4>
    Federal Custer of Excellence "MERGE"<br>
    Central Facility of Chemnitz University of Technology<br>
    Reichenhainer Straße 70<br>
    09126 Chemnitz, Germany<br>
    <br>
    Mag.Iur. Luciana Schollmeier<br>
    <br>
    <span class="contactdataformat">Phone</span>:<a href="https://www.tu-chemnitz.de/urz/mail/adr.php?1KzQ5LTM3MS01MzEzMzYyMg==" onclick="return hs.htmlExpand(this, {src:'https://www.tu-chemnitz.de/urz/mail/adrx.php?1KzQ5LTM3MS01MzEzMzYyMg==&amp;l=en',objectType:'iframe',height:200,width:350,headingText:'Data protection'})">+49-371-531...</a><br>
    <span class="contactdataformat">Fax</span>:<a href="https://www.tu-chemnitz.de/urz/mail/adr.php?1KzQ5LTM3MS01MzE4MzM2MjI=" onclick="return hs.htmlExpand(this, {src:'https://www.tu-chemnitz.de/urz/mail/adrx.php?1KzQ5LTM3MS01MzE4MzM2MjI=&amp;l=en',objectType:'iframe',height:200,width:350,headingText:'Data protection'})">+49-371-531...</a><br>

<br>

</div>
