<?php echo $this->doctype(); ?>

<html lang="en">
<head>
 <title>MB/IST: MERGE</title>
 <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
 <meta http-equiv="Last-Modified" content="Fri, 26 Apr 2013 02:18:31 GMT">
 <meta http-equiv="Last-Modified-Date" content="2013-04-26">
 <meta name="author" content="Om choudhary - Choudharyom@hotmail.com">
 <meta name="copyright" content="MB/IST">
 <meta name="country" content="de">
 <meta name="coverage" content="Worldwide">
 <meta name="description" content="Chemnitz University of Technology, MB/IST, MERGE: Studieren in Chemnitz. Wissen, was gut ist.">
 <meta name="keywords" content="Chemnitz University of Technology, MB/IST MERGE ">
 <meta name="language" content="en">
 <meta name="organization-Email" content="thomas.friedrich@mb.tu-chemnitz.de">
 <meta name="revisit-after" content="5 days">
 <meta name="robots" content="index,follow">
 
 <link rel="stylesheet" type="text/css" href="/tucal/css/standard.css" media="screen" title="screen">
 <link rel="stylesheet" type="text/css" href="/tucal/css/print.css" media="print">
 <link rel="alternate stylesheet" type="text/css" href="/tucal/css/text.css" media="screen" title="text">
 <!--[if IE 6]>
 <link rel="stylesheet" type="text/css" href="/tucal/css/ie6.css" media="screen" />
 <![endif]-->
 <script src="/tucal/js/standard.js" type="text/javascript"></script><style type="text/css"></style>
 <script src="/tucal/js/highslide/highslide-full.min.js" type="text/javascript"></script>
 <script src="/tucal/js/highslide/highslide.cfg.js.en" type="text/javascript"></script>
 <link rel="stylesheet" type="text/css" href="/tucal/js/highslide/highslide.css">
 <script src="/tucal/js/jquery.js" type="text/javascript"></script>
 <script src="/tucal/js/jquery-ui.js" type="text/javascript"></script>
 <link rel="stylesheet" type="text/css" href="/tucal/css/jquery-ui.css">

 <link rel="shortcut icon" href="/tucal/img/tuc.png">
 <style type="text/css"><!--
@import url("inc/css/layout.css");
--></style>

<style type="text/css">.highslide img {cursor: url(/tucal/js/highslide/graphics/zoomin.cur), pointer !important;}.highslide-viewport-size {position: fixed; width: 100%; height: 100%; left: 0; top: 0}</style></head>
    <body>

        <div class="container">
            <?php echo $this->content; ?>

        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
