<div class="hero-unit">
<div style="font-family:verdana;padding:20px;width:900px;height:400px;border-radius:20px;border:0px solid #EE872A;">


   <a href="/Shibboleth.sso/Login?target=/~omc/Testing/public/logger">Logger</a> | <a href="./register/">Registration</a> | <a href="./export/download">Download</a><br /><br />
<div>
    <h1>This is the index page for Export</h1>
    <?php if(isset($form)){
        echo '<b><font color="red">';
        echo $form;
        echo '</font></b>';
    }?>

</div>
